JETHERNET::W5500Socket
NAME
JETHERNET::W5500Socket
SYNOPSIS
Inherits JETHERNET::NetSock.
Public Member Functions
bool open (NetIP ip, uint16_t port, SockConnectMode mode) override
bool close () override
close socket
bool connectTCP (NetIP ip, uint16_t port) override
connect to TCP server
bool disconnect () override
disconnect socket
int write (uint8_t *dataIn, uint16_t len) override
send data
int read (uint8_t *dataOut, uint16_t len) override
receive data
uint8_t getWizSocketStatus () const
int getSocketNum () const
bool isConnected () const
check if socket is connected/open
operator bool () const
W5500Socket (int sn)
Friends
class W5500HC
Detailed Description
Definition at line 17 of file W5500Socket.hpp.
Constructor & Destructor Documentation
JETHERNET::W5500Socket::W5500Socket ()
Definition at line 91 of file W5500Socket.cpp.
JETHERNET::W5500Socket::W5500Socket (int sn)
Definition at line 94 of file W5500Socket.cpp.
Member Function Documentation
bool JETHERNET::W5500Socket::close () [override], [virtual]
close socket
Returns
true if socket successfully closed
Implements JETHERNET::NetSock.
Definition at line 37 of file W5500Socket.cpp.
bool JETHERNET::W5500Socket::connectTCP (NetIP ip, uint16_t port) [override], [virtual]
connect to TCP server
Parameters
ip destination IP
port destination port
Returns
true if successfully connected
Note
will attempt to open socket if not open when called
Implements JETHERNET::NetSock.
Definition at line 41 of file W5500Socket.cpp.
References isConnected(), and open().
bool JETHERNET::W5500Socket::disconnect () [override], [virtual]
disconnect socket
Returns
true if socket successfully disconnected from server
Implements JETHERNET::NetSock.
Definition at line 60 of file W5500Socket.cpp.
int JETHERNET::W5500Socket::getSocketNum () const
Definition at line 78 of file W5500Socket.cpp.
uint8_t JETHERNET::W5500Socket::getWizSocketStatus () const
Definition at line 98 of file W5500Socket.cpp.
bool JETHERNET::W5500Socket::isConnected () const [virtual]
check if socket is connected/open
Returns
true if socket is open or connected
Warning
misleading name, will probably correct in the future
Implements JETHERNET::NetSock.
Definition at line 82 of file W5500Socket.cpp.
Referenced by connectTCP(), read(), and write().
bool JETHERNET::W5500Socket::open (NetIP ip, uint16_t port, SockConnectMode mode) [override], [virtual]
Parameters
ip destination IP
port destination port
mode connection
Returns
true if socket successfully opened
Implements JETHERNET::NetSock.
Definition at line 32 of file W5500Socket.cpp.
Referenced by connectTCP().
JETHERNET::W5500Socket::operator bool () const
Definition at line 87 of file W5500Socket.cpp.
int JETHERNET::W5500Socket::read (uint8_t * dataOut, uint16_t len) [override], [virtual]
receive data
Parameters
dataOut buffer for data to be received into
len number of bytes to be received
Returns
number of bytes read
Implements JETHERNET::NetSock.
Definition at line 71 of file W5500Socket.cpp.
References isConnected().
int JETHERNET::W5500Socket::write (uint8_t * dataIn, uint16_t len) [override], [virtual]
send data
Parameters
dataIn data to be written
len number of bytes to be written
Returns
number of bytes written
Implements JETHERNET::NetSock.
Definition at line 64 of file W5500Socket.cpp.
References isConnected().
Friends And Related Symbol Documentation
friend class W5500HC [friend]
Definition at line 36 of file W5500Socket.hpp.
Author
Generated automatically by Doxygen for CSTM32 Led Controller from the source code.