.TH "JETHERNET::W5500Config" 3 "Version 0.1.1" "CSTM32 Led Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JETHERNET::W5500Config
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SPI_HandleTypeDef * \fBspi\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBchipSelectPort\fP"
.br
.ti -1c
.RI "uint16_t \fBchipSelectPin\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBresetPort\fP"
.br
.ti -1c
.RI "uint16_t \fBresetPin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBW5500Interface\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t JETHERNET::W5500Config::chipSelectPin"

.PP
Definition at line \fB30\fP of file \fBW5500Interface\&.hpp\fP\&.
.SS "GPIO_TypeDef* JETHERNET::W5500Config::chipSelectPort"

.PP
Definition at line \fB29\fP of file \fBW5500Interface\&.hpp\fP\&.
.SS "uint16_t JETHERNET::W5500Config::resetPin"

.PP
Definition at line \fB32\fP of file \fBW5500Interface\&.hpp\fP\&.
.SS "GPIO_TypeDef* JETHERNET::W5500Config::resetPort"

.PP
Definition at line \fB31\fP of file \fBW5500Interface\&.hpp\fP\&.
.SS "SPI_HandleTypeDef* JETHERNET::W5500Config::spi"

.PP
Definition at line \fB28\fP of file \fBW5500Interface\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32 Led Controller from the source code\&.
