.TH "JETHERNET::W5500Config" 3 "Thu Apr 25 2024" "Version 0.1.1" "CSTM32LedController" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JETHERNET::W5500Config
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SPI_HandleTypeDef * \fBspi\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBchipSelectPort\fP"
.br
.ti -1c
.RI "uint16_t \fBchipSelectPin\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBresetPort\fP"
.br
.ti -1c
.RI "uint16_t \fBresetPin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file W5500Interface\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32LedController from the source code\&.
