.TH "JETHERNET::NetConfig" 3 "Version 0.1.1" "CSTM32 Led Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JETHERNET::NetConfig \- Network configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <NetConfig\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcString\fP (char *buf)"
.br
.RI "Print formatted network config to output buffer\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNetMAC\fP \fBmac\fP"
.br
.ti -1c
.RI "\fBNetIP\fP \fBip\fP"
.br
.ti -1c
.RI "\fBNetIP\fP \fBsubnet\fP"
.br
.ti -1c
.RI "\fBNetIP\fP \fBgateway\fP"
.br
.ti -1c
.RI "\fBNetIP\fP \fBdns\fP"
.br
.ti -1c
.RI "bool \fBdhcpEnabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Network configuration\&. 


.PP
\fBSee also\fP
.RS 4
\fBNetIP\fP 
.PP
\fBNetMAC\fP 
.PP
\fBNetSock\fP 
.PP
\fBEthernetHC\fP 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBNetConfig\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int JETHERNET::NetConfig::cString (char * buf)"

.PP
Print formatted network config to output buffer\&. 
.PP
\fBNote\fP
.RS 4
maximum 152 characters written (153 w/ null char) 
.RE
.PP
\fBParameters\fP
.RS 4
\fIbuf\fP output buffer 
.RE
.PP
\fBReturns\fP
.RS 4
number of bytes written 
.RE
.PP

.PP
Definition at line \fB13\fP of file \fBNetConfig\&.cpp\fP\&.
.PP
References \fBJETHERNET::NetIP::cString()\fP, and \fBJETHERNET::NetMAC::cString()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool JETHERNET::NetConfig::dhcpEnabled"

.PP
Definition at line \fB29\fP of file \fBNetConfig\&.hpp\fP\&.
.SS "\fBNetIP\fP JETHERNET::NetConfig::dns"

.PP
Definition at line \fB28\fP of file \fBNetConfig\&.hpp\fP\&.
.SS "\fBNetIP\fP JETHERNET::NetConfig::gateway"

.PP
Definition at line \fB27\fP of file \fBNetConfig\&.hpp\fP\&.
.SS "\fBNetIP\fP JETHERNET::NetConfig::ip"

.PP
Definition at line \fB25\fP of file \fBNetConfig\&.hpp\fP\&.
.SS "\fBNetMAC\fP JETHERNET::NetConfig::mac"

.PP
Definition at line \fB24\fP of file \fBNetConfig\&.hpp\fP\&.
.SS "\fBNetIP\fP JETHERNET::NetConfig::subnet"

.PP
Definition at line \fB26\fP of file \fBNetConfig\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32 Led Controller from the source code\&.
