.TH "JETHERNET::W5500Interface" 3 "Version 0.1.1" "CSTM32 Led Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JETHERNET::W5500Interface
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinitChip\fP ()"
.br
.ti -1c
.RI "bool \fBinitDHCP\fP (\fBW5500Socket\fP &sock, \fBNetConfig\fP *conf, uint16_t timeoutMs)"
.br
.ti -1c
.RI "void \fBinitDNS\fP (\fBW5500Socket\fP &sock)"
.br
.ti -1c
.RI "void \fBtriggerReset\fP ()"
.br
.ti -1c
.RI "\fBW5500Interface\fP (\fBW5500Interface\fP const &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBW5500Interface\fP const &)=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBW5500Interface\fP & \fBinstance\fP ()"
.br
.ti -1c
.RI "static bool \fBinit\fP (\fBW5500Config\fP config)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBW5500HC\fP"
.br
.ti -1c
.RI "void \fBreadBuffer\fP (uint8_t *buf, uint16_t len)"
.br
.ti -1c
.RI "void \fBwriteBuffer\fP (uint8_t *buf, uint16_t len)"
.br
.ti -1c
.RI "uint8_t \fBreadByte\fP ()"
.br
.ti -1c
.RI "void \fBwriteByte\fP (uint8_t byte)"
.br
.ti -1c
.RI "void \fBenableChipSelect\fP ()"
.br
.ti -1c
.RI "void \fBdisableChipSelect\fP ()"
.br
.ti -1c
.RI "void \fBCB_DHCP_IPAssigned\fP ()"
.br
.ti -1c
.RI "void \fBCB_DHCP_IPConflict\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBW5500Interface\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool JETHERNET::W5500Interface::init (\fBW5500Config\fP config)\fR [static]\fP"

.PP
Definition at line \fB137\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "bool JETHERNET::W5500Interface::initChip ()"

.PP
Definition at line \fB89\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "bool JETHERNET::W5500Interface::initDHCP (\fBW5500Socket\fP & sock, \fBNetConfig\fP * conf, uint16_t timeoutMs)"

.PP
Definition at line \fB107\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "void JETHERNET::W5500Interface::initDNS (\fBW5500Socket\fP & sock)"

.PP
Definition at line \fB132\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "\fBW5500Interface\fP & JETHERNET::W5500Interface::instance ()\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "void JETHERNET::W5500Interface::triggerReset ()"

.PP
Definition at line \fB82\fP of file \fBW5500Interface\&.cpp\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "void CB_DHCP_IPAssigned ()\fR [friend]\fP"

.PP
Definition at line \fB67\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "void CB_DHCP_IPConflict ()\fR [friend]\fP"

.PP
Definition at line \fB73\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "void disableChipSelect ()\fR [friend]\fP"

.PP
Definition at line \fB30\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "void enableChipSelect ()\fR [friend]\fP"

.PP
Definition at line \fB25\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "void readBuffer (uint8_t * buf, uint16_t len)\fR [friend]\fP"

.PP
Definition at line \fB35\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "uint8_t readByte ()\fR [friend]\fP"

.PP
Definition at line \fB57\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "friend class \fBW5500HC\fP\fR [friend]\fP"

.PP
Definition at line \fB48\fP of file \fBW5500Interface\&.hpp\fP\&.
.SS "void writeBuffer (uint8_t * buf, uint16_t len)\fR [friend]\fP"

.PP
Definition at line \fB46\fP of file \fBW5500Interface\&.cpp\fP\&.
.SS "void writeByte (uint8_t byte)\fR [friend]\fP"

.PP
Definition at line \fB63\fP of file \fBW5500Interface\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32 Led Controller from the source code\&.
