.TH "JMQTT::ClientConfig" 3 "Thu Apr 25 2024" "Version 0.1.1" "CSTM32LedController" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMQTT::ClientConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MQTTVersion \fBversion\fP = MQTTVersion::MQTT311"
.br
.ti -1c
.RI "\fBJETHERNET::NetIP\fP \fBbrokerIP\fP = 0"
.br
.ti -1c
.RI "uint16_t \fBbrokerPort\fP = 0"
.br
.ti -1c
.RI "string \fBclientName\fP = 'JMQTTClient'"
.br
.ti -1c
.RI "string \fBusername\fP = ''"
.br
.ti -1c
.RI "string \fBpassword\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file Client\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32LedController from the source code\&.
