.TH "JMQTT::Message" 3 "Thu Apr 25 2024" "Version 0.1.1" "CSTM32LedController" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMQTT::Message
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtopic\fP = ''"
.br
.ti -1c
.RI "string \fBpayload\fP = ''"
.br
.ti -1c
.RI "QOS \fBqos\fP = QOS::QOS0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file Client\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32LedController from the source code\&.
