.TH "JMQTT::Message" 3 "Version 0.1.1" "CSTM32 Led Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMQTT::Message
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtopic\fP = ''"
.br
.ti -1c
.RI "string \fBpayload\fP = ''"
.br
.ti -1c
.RI "QOS \fBqos\fP = QOS::QOS0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBClient\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string JMQTT::Message::payload = ''"

.PP
Definition at line \fB29\fP of file \fBClient\&.hpp\fP\&.
.SS "QOS JMQTT::Message::qos = QOS::QOS0"

.PP
Definition at line \fB30\fP of file \fBClient\&.hpp\fP\&.
.SS "string JMQTT::Message::topic = ''"

.PP
Definition at line \fB28\fP of file \fBClient\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32 Led Controller from the source code\&.
