.TH "JMQTT::ClientConfig" 3 "Version 0.1.1" "CSTM32 Led Controller" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMQTT::ClientConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MQTTVersion \fBversion\fP = MQTTVersion::MQTT311"
.br
.ti -1c
.RI "\fBJETHERNET::NetIP\fP \fBbrokerIP\fP = 0"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBbrokerPort\fP = 0"
.br
.ti -1c
.RI "string \fBclientName\fP = 'JMQTTClient'"
.br
.ti -1c
.RI "string \fBusername\fP = ''"
.br
.ti -1c
.RI "string \fBpassword\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB39\fP of file \fBClient\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBJETHERNET::NetIP\fP JMQTT::ClientConfig::brokerIP = 0"

.PP
Definition at line \fB41\fP of file \fBClient\&.hpp\fP\&.
.SS "\fBuint16_t\fP JMQTT::ClientConfig::brokerPort = 0"

.PP
Definition at line \fB42\fP of file \fBClient\&.hpp\fP\&.
.SS "string JMQTT::ClientConfig::clientName = 'JMQTTClient'"

.PP
Definition at line \fB43\fP of file \fBClient\&.hpp\fP\&.
.SS "string JMQTT::ClientConfig::password = ''"

.PP
Definition at line \fB45\fP of file \fBClient\&.hpp\fP\&.
.SS "string JMQTT::ClientConfig::username = ''"

.PP
Definition at line \fB44\fP of file \fBClient\&.hpp\fP\&.
.SS "MQTTVersion JMQTT::ClientConfig::version = MQTTVersion::MQTT311"

.PP
Definition at line \fB40\fP of file \fBClient\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32 Led Controller from the source code\&.
