.TH "JMQTT::PAHONetwork" 3 "Thu Apr 25 2024" "Version 0.1.1" "CSTM32LedController" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JMQTT::PAHONetwork
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBread\fP (uint8_t *buffer, uint16_t len, uint16_t timeoutMs)"
.br
.ti -1c
.RI "int \fBwrite\fP (uint8_t *buffer, uint16_t len, uint16_t timeoutMs)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBJETHERNET::NetSock\fP * \fBsock\fP = nullptr"
.br
.ti -1c
.RI "\fBClientConfig\fP \fBconf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file PAHOClient\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CSTM32LedController from the source code\&.
